version: "3"
services:
  stories:
    build: .
    volumes:
      - stories:/app/story
    ports:
      - 80:3000
volumes:
  # This volume is used to persist story data for the stories service
  stories: 