apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce # I need to review this
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi